spring:
  profiles:
    active: local

mqtt:
  enabled: true

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    clean-disabled: true

  hikari:
    maximum-pool-size: 10
    minimum-idle: 2
    idle-timeout: 30000
    max-lifetime: 1800000
    connection-timeout: 20000


